Test search

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,12 +24,12 @@ jobs:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: Check for test
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          if [ -f BacodeUtilTest.kt ]; then
+            echo "Barcode util test found!"
+          else
+            echo "Test script not found" > error.txt
+            exit 1
+          fi
+        continue-on-error: true
