Added environment prep

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,6 +23,7 @@ jobs:
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
+      - uses: fwilhe2/setup-kotlin@main
 
       - name: Check for test
         run: |
@@ -34,3 +35,13 @@ jobs:
             exit 1
           fi
         continue-on-error: true
+
+      - name: Prepare environment
+        run: |
+          if [ -f error.txt ]; then
+            echo "Found error!"
+            exit 1
+          else             
+            kotlinc src/main/kotlin/util/BarcodeUtilTest.kt -include-runtime -d BarcodeUtilTest.jar
+            kotlin -classpath BarcodeUtilTest.jar org.junit.runner.JUnitCore util.BarcodeUtilTest
+          fi
